### ISSUE TITLE
Skin have since Version 2.11.1 not the second skin layer.

### ISSUE THREAD

**Issue by Chibilena** [MinecraftLibraries/NPCLib#142] opened 2021-02-02 14:18 UTC
**Describe the bug**
Since version 2.11.1, the skins of the NPC's have no second layer.
https://prnt.sc/y0z9q6

`		npc = Citybuild.getInstance().getLibrary().createNPC(text);
		npc.setItem(NPCSlot.MAINHAND, new ItemStack(Material.IRON_HOE));
		npc.setItem(NPCSlot.OFFHAND, new ItemStack(Material.BREAD));
		npc.setSkin(new Skin("ewogICJ0aW1lc3RhbXAiIDogMTYxMjI3Mzc3NzcxMywKICAicHJvZmlsZUlkIiA6ICJmNThkZWJkNTlmNTA0MjIyOGY2MDIyMjExZDRjMTQwYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJ1bnZlbnRpdmV0YWxlbnQiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWFkNmQ3MjY3ZTM3MmFlYzE2ZmY5MzAyZjFkYWJmMTMzNmIxMDRjMGI1NTQxODYwZWI4NjcyYTIwYTk5YjVlZiIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9", "lojRH0FW/gHNwKCzaGV3uyKipydjbV6zMoGnHaBk1lnWDghW/Qkv7qU34BgODyToIXyxYi45rrZFYr7nqqYzB+Czdig0oPXl1VPHxNq42ZD8pH5qJwrctokZZFajCKmRxBreQEL3l6EWcpdhMXYkiWoWy0Zn2ynY2VfPdxuVZFOQjQBCjf4EBI7YgwXwJP7179HlP2QbYEhvIzLNQGljBarMnWTEU3UGj48zeXnGpoDfFowXj3cDLgKWQG0IMSjHFnZXEmUsnhV24ry+OF23It1foa6dn2bNejDViLhbLCWcrBh7QIDfi4B6ncJy1xGq+qEMXAQEa89miAXM30sO3LXp7oJtWcyubw2+1eLQqGR5XJmfKZsTPB+k7w+YrpJlhVrbZtoFifwXpX4lpkW5cwgVimdkC58z88RbPkRLtohZTBsXzSf7C1SHwj3AMccRN9LMJmj21WomclKw4YbsoWrOCm8NSFL3KSonTq2w2z/MHC3E8UcqbQkQP5NjBvF+1kLs+c1mB0zeqKRc+IXDSjTbULF/1ozdMUN6j7cvQnNfnPmqqJGf4VwAggx4XjIxdOLP9x927N+mY6YITbR87XN3xJ6y0xtFcgz5C2TTVYG+g/UyL0/iZ98IEP9GyAb08vCSIvCtvpmUZPhzep8PJkS0pNPHf0ZlsMnO3SytHyk="));
		npc.create();`

**NPCLib JAR name**
E.g. npclib-plugin-2.11.1-SNAPSHOT.jar

**Server version**
paper 1.16.5

**Comment by Mooselk** [comment] 2021-02-03 18:30
Could you quickly test this no an earlier version of the game, 1.8.8 preferably. I’m pretty sure I know what the issue is I just don’t have a means of testing it myself at the moment.

**Comment by Chibilena** [comment] 2021-02-04 09:06
I have now tested the whole thing on version Spigot 1.8.8 and it works there without problems.
https://prnt.sc/y8zwug

**Comment by Mooselk** [comment] 2021-02-05 00:29
Okay good, I’ll create a pr soon to fix it.

**Comment by JitseB** [comment] 2021-02-24 21:33
This is released in the pre-release 2.12.2-SNAPSHOT, but I don't recommend to use it for production servers yet. Still work in progress. I do invite you to test to see if this issue in specific has been resolved. Closing issue for now.

**Closed by JitseB** 2021-02-24 21:33 UTC
Labels: bug
