### ISSUE TITLE
NPCLib Console Spam and extreme server lag with 20+ players.

### ISSUE THREAD

**Issue by Lucaskyy** [MinecraftLibraries/NPCLib#95] opened 2020-06-25 18:40 UTC
**Describe the bug**
The console gets spammed and the server lags to nearly a halt with 30+ players.
This gets spammed around 20 times in 1 single second.

`[20:21:58 ERROR]: NPCLib Error in onPacketInAsync().
java.lang.NullPointerException`

**NPCLib usage option**
3

**NPCLib JAR name**
Shaded: 2.7.2-SNAPSHOT

**Server version**
CraftBukkit version git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**To Reproduce**
- Place some NPC's with NPCHitEvent etc, then let 30+ people on the server and the console should be spammed.

**Expected behavior**
NO lag, and errors.

**Screenshots**
https://imgur.com/a/K6DvBaI

**Additional context**
We want to make a server using NPC's and the NPCLib(rary) and as of now this is not possible if we have more than 25/30 players.

**Comment by JitseB** [comment] 2020-06-25 18:53
Hi, thanks for creating this issue ticket!

Can you try to track down the full stack trace? This is something I can't reproduce on my development server. The fact that something is null doesn't help me at all, I need a little bit more information.

You can get the full stack trace to print when the error is printed less often (also when the error just started printing).

**Comment by Lucaskyy** [comment] 2020-06-25 19:11
We get the same as https://github.com/MinecraftLibraries/NPCLib/issues/89, we are running 2.7.2 which had a fix for that issue but it came back.

**Comment by JitseB** [comment] 2020-06-25 19:30
Ah, well in that case. This issue is a duplicate of #89. Closing issue.

I'd like to continue this conversation in issue #89.

**Closed by JitseB** 2020-06-25 19:30 UTC
Labels: bug
