### ISSUE TITLE
Feature (NPC laying down)

### ISSUE THREAD

**Issue by BlazingTide** [MinecraftLibraries/NPCLib#123] opened 2020-10-04 16:39 UTC
There should be a feature where the npc is laying down (Maybe add that as an NPC state). It would be similar to npc on the bed.

**Comment by Mooselk** [comment] 2020-11-22 16:37
@BlazingTide I’m going to start work on this soon, probably after I fix the crouch state for 1.14+

**Comment by JitseB** [comment] 2020-11-24 20:24
Duplicate of #98

**Closed by JitseB** 2020-11-24 20:24 UTC
Labels: bug
