### ISSUE TITLE
The NPC is invisible

### ISSUE THREAD

**Issue by Angxstupst** [MinecraftLibraries/NPCLib#140] opened 2021-02-01 18:38 UTC
**Describe the bug**
The NPC is invisible. The hologram, on the other hand, is visible

**NPCLib usage option**
Maven dependency

**NPCLib JAR name**
E.g. npclib-plugin-2.11.1-SNAPSHOT.jar

**Server version**
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Screenshots**
![2021-02-01_19 35 26](https://user-images.githubusercontent.com/70912869/106502837-2a8ab380-64c5-11eb-9398-1632bf899bff.png)

**Comment by JitseB** [comment] 2021-02-01 20:09
First of all, why are you still using version 2.0.1-SNAPSHOT? Second of all, duplicate of #124, so why not append to that?

**Comment by Angxstupst** [comment] 2021-02-01 20:28
Ups, sorry. I'm using the latest version. 2.11.1

**Comment by JitseB** [comment] 2021-02-03 20:39
Ok, then I'm closing this issue. We shall continue this thread in #124.

**Closed by JitseB** 2021-02-03 20:39 UTC
Labels: bug
