### ISSUE TITLE
Cannot use on 1.12.2 Paper

### ISSUE THREAD

**Issue by Xierip** [MinecraftLibraries/NPCLib#136] opened 2021-01-12 21:48 UTC
**Describe the bug**
Just cannot use this lib.

**NPCLib usage option**
I tried in all options.

**NPCLib JAR name**
npclib-plugin-2.11.1-SNAPSHOT.jar

**Server version**
Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**To Reproduce**
- Used code  
![image](https://user-images.githubusercontent.com/12198060/104377740-3539d480-5527-11eb-95f8-e20c34c6736d.png)

- See error 
![image](https://user-images.githubusercontent.com/12198060/104377806-4c78c200-5527-11eb-9f81-9d9b02b5c2d8.png)

**Expected behavior**
I want to spawn a NPC...

**Comment by Mooselk** [comment] 2021-01-13 15:27
Can you provide the full class?

**Comment by Xierip** [comment] 2021-01-14 15:39
@Mooselk 
![image](https://user-images.githubusercontent.com/12198060/104612754-d3907c00-5686-11eb-84aa-0c7bf5923712.png)
https://github.com/Xierip/TestNpcLib

**Comment by Xierip** [comment] 2021-01-14 15:40
It happens on everytime :/

**Comment by Mooselk** [comment] 2021-01-15 16:11
Looks like an issue with tinyprotocol, it’s probably incompatible with paper. I don’t know enough about it to fix it.

**Comment by JitseB** [comment] 2021-01-18 13:18
I’ll see what I can do about it at the end of the week. I’m a bit busy at the moment.

**Comment by JitseB** [comment] 2021-01-23 15:07
Can you link the URL to your specified PaperSpigot version? I can't seem to reproduce this issue using the latest version of PaperSpigot...

From what I see in the code is that there's a pending and confirmed array for the server connection class, at least in the 1.16.5 version. It doesn't seem plausible that this is what is causing this strange null pointer, so I will investigate that a little bit more.

**Comment by Xierip** [comment] 2021-01-23 15:47
@JitseB This is weird, I runned now this same server, and now its working O_o
I added it to minigame plugin and its working fine too.

**Comment by Xierip** [comment] 2021-01-23 15:51
But on lobby plugin for minigame not working, server setup is equal
![image](https://user-images.githubusercontent.com/12198060/105606703-34ad0380-5d9b-11eb-85c9-2eb2cded4f68.png)

**Comment by Xierip** [comment] 2021-01-23 15:53
Oh ok, its issue with old protocollib plugin i think.
Thats really weird

**Comment by JitseB** [comment] 2021-01-23 16:01
Extraordinary. ProtocolLib should not interfere with TinyProtocollib. Good to hear that you got it working now!
Also makes sense now that I can't reproduce it. I only have NPCLib and a test plugin on my server.
Closing issue, if you happen to find that this issue is caused by something else, please do tell!

**Closed by JitseB** 2021-01-23 16:01 UTC
Labels: bug
